### ISSUE TITLE
Problem with Square Brackets

### ISSUE THREAD

**Issue by ak2yny** [nikita488/raven-formats#1]
If square brackets are used in the path, Xmlb can't find the file: https://discord.com/channels/449510825385000960/449515176312569856/1073669060413370489

I can repeat the bug:
```bat
json2xmlb.exe "[Folder]\attilan1.pkgb.xml" "[Folder]\attilan1.pkgb"
```
Error message:
```
Traceback (most recent call last):
  File "xmlb (raven-formats by nikita488).py", line 214, in <module>
  File "xmlb (raven-formats by nikita488).py", line 200, in main
FileNotFoundError: [Errno 2] No such file or directory: 'attilan1.pkgb.xml'
[11304] Failed to execute script 'xmlb (raven-formats by nikita488)' due to unhandled exception!
```
I can repeat that with Xmlb.exe installed through pip as well.

**Comment by ak2yny** [comment]
It seems to be an issue with `Path`: https://github.com/nikita488/raven-formats/blob/1092cdf8869efa5bef8428b0f8d539df9635fa63/src/raven_formats/xmlb.py#L2
And/or glob: https://github.com/nikita488/raven-formats/blob/1092cdf8869efa5bef8428b0f8d539df9635fa63/src/raven_formats/xmlb.py#L1
https://stackoverflow.com/questions/2595119/glob-and-bracket-characters

Apparently, you can use [glob.escape](https://docs.python.org/3.4/library/glob.html#glob.escape)
