### ISSUE TITLE
Error when decompiling XML1 Xbox ZSM file(s)

### ISSUE THREAD

**Issue by ak2yny** [nikita488/raven-formats#7]
Tried decompiling beast_m.zsm from the Xbox version of X-Men Legends (1).

Error message:
```
Traceback (most recent call last):
  File "C:\Users\xx\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\xx\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\xx\AppData\Local\Programs\Python\Python310\Scripts\zsnd.exe\__main__.py", line 7, in <module>
  File "D:\GitHub\raven-formats\src\raven_formats\zsnd.py", line 465, in main
    decompile(input_file, output_file)
  File "D:\GitHub\raven-formats\src\raven_formats\zsnd.py", line 436, in decompile
    json.dump(read_zsnd(zsnd_path, output_path), json_file, indent=4)
  File "D:\GitHub\raven-formats\src\raven_formats\zsnd.py", line 298, in read_zsnd
    hash_string = hash2str(hash_value)
  File "D:\GitHub\raven-formats\src\raven_formats\zsnd.py", line 149, in hash2str
    hash_strings = json.load(hashes_file)
  File "C:\Users\xx\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\xx\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 335, in loads
    raise JSONDecodeError("Unexpected UTF-8 BOM (decode using utf-8-sig)",
json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
```
This is the error message from a modified version of Zsnd. The error persists with the current version on this branch, however (unfortunately, I didn't copy the error message from that version).

Steps to reproduce:
- Get a ZSM file from the Xbox version of XML1 ([beast_m.zip](https://github.com/nikita488/raven-formats/files/13650661/beast_m.zip))
- Try to decompile it using the command in the readme (`zsnd.py -d beast_m.zsm beast_m.json`)

**Comment by ak2yny** [comment]
Stupid mistake. Stands in big letters: `json.load(hashes_file)` (and where it seems to load the file).
Easy fix by modifying my zsnd_hashes.json
